### ISSUE TITLE
Subir lecciones 1-4

### ISSUE THREAD

**Issue by rnovec** [disoftw/regular-expressions#1]
Subir los temas 

1. _What are Regular Expressions?_
2. _Literal Matches_
3. _The Dot_
4. _Matching Special Characters_

de la plataforma [SoloLearn](https://www.sololearn.com/)

![image](https://user-images.githubusercontent.com/36168284/87904072-24e6e800-ca23-11ea-9787-327f6eba4bf4.png)
![image](https://user-images.githubusercontent.com/36168284/87904120-46e06a80-ca23-11ea-858a-cfb961afe711.png)

## Paso 1
- Descargar la app movil
- Descargar un emulador de Android para Windows como: [BlueStacks](https://www.bluestacks.com/download.html)

![image](https://user-images.githubusercontent.com/36168284/87903936-d8031180-ca22-11ea-90a8-f4155d2c3ad6.png)

## Paso 2
- **Forkear** el proyecto y **clonarlo** desde su cuenta a su maquina.
- Crear una rama llamada `feature/parte1`

## Paso 3
- Ubicar la lección en la aplicación.
- Reescribir cada lección en un archivo [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) respetando la sintaxis de negritas, citas, código, etc...
- Un archivo markdown por lección con el nombre de la lección, ejemplo: `1. what-are-regular-expressions.md`
- Puedes guiarte de este archivo de [ejemplo](https://github.com/disoftw/regular-expressions/blob/master/en/README.md)
## Paso 4 (Opcional)
- Traducir la lección. Crear un archivo traducido al español correspondiente a cada lección

## Paso 5
- Guardar cambios, hacer commits necesarios
- Subir cambios y enviar un **pull request** a `develop`

**Comment by IvanMadera** [comment]
Me tome la libertad de realizar esta tarea, intentare subirla en un momento

**Comment by rnovec** [comment]
Resuelto por @IvanMadera en #5. Ninguna observación, gracias. Tengo pendiente tu certificado
